### ISSUE TITLE
Filtering by `id` is using wildcard search.

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#100]
**Describe the bug**
When providing an id as a filter, Soul is running a wildcard search instead of providing items of that id

**To Reproduce**
1. Run Soul
2. Enter this URL:
```
http://localhost:8000/api/tables/albums/rows?_filters=ArtistId:2
```

**Expected behavior**
I expected to receive albums for the `ArtistId:2`. Instead I received albums where the `ArtistId` included `2`

The documentation suggests filter works on id:
![image](https://github.com/thevahidal/soul/assets/1108513/55baa7ae-6536-4efa-8764-352975923e8c)

**Screenshots**
![image](https://github.com/thevahidal/soul/assets/1108513/722d41b7-d45b-42dd-a76d-1775bfa590c3)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by thevahidal** [comment]
Fixed in the latest release.
