### ISSUE TITLE
Publish `View` via API

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#101]
**Is your feature request related to a problem? Please describe.**
To enrich the data returned by my API I wish to collate the related data in SQLite.   

I have done this with a SQLite view.  The view introduces fields from related tables.

But, the `view` is not treated as a `table` in `Soul` - so I cannot retrieve it.

**Describe the solution you'd like**
It would be great if Soul exposed SQLite views in the database

**Update**

Have attached a chinook database with an example of a view that is used to enrich the `invoice_items` table.
[chinook_with_view.db.zip](https://github.com/thevahidal/soul/files/12051707/chinook_with_view.db.zip)

**Comment by thevahidal** [comment]
I understand you, the only problem that I have with showing views with the same `/tables/...` endpoints is that it's a bit unintuitive as basically they're different type of entities.
Do you have any suggestion for this?

**Comment by IanMayo** [comment]
I _don´t think_ they are different types of entity.  To a consumer of the API they´re the same - they´ŕe both just arrays of data items.  The consumer has an end-point that provides rows of data.  The consumer doesn´t need to know if it´s a physical table, or a logical combination of tables collated behind the scenes.

I _think_ it will _just work_.
