### ISSUE TITLE
Soul keeps crashing when invalid key is passed to the `_extend` field

### ISSUE THREAD

**Issue by AbegaM** [thevahidal/soul#111]
## Describe the Bug
* When a request is sent to the `/api/tables/invoices/rows?_extend=CustomerId` API endpoint, soul returns data from both the `invoices` and `customer` tables by extending the request using the `CustomerId` field. However, if an invalid foreign key is used in the `_extend` parameter, such as `customerId` or `Total`, soul returns an error message stating `Foreign key not found`. Currently, if an invalid key is passed, soul crashes and needs to be manually restarted. The reason that soul crashes is because, in the `rows.js` file the code is using the `res.json.send()` function inside a `map` function

## To Reproduce

1. Send a request to the following URL in your browser: `localhost:8000/api/tables/invoices/rows?_extend=customerId`
2. An error will be displayed in the browser, as shown below, and soul will crash:

    ```js
    {
      "message": "Foreign key not found",
      "error": {}
    }
    ```

## Expected Behavior

* Soul should return an error message if an invalid foreign key is passed using the `_extend` parameter, but it should not crash

**Comment by IanMayo** [comment]
Could the error message include the invalid foreign key, please? 

(just in case multiple keys are provided)

**Comment by AbegaM** [comment]
@IanMayo sure i will modify the error message
