### ISSUE TITLE
Soul error on single quote

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#146]
This issue is related to the use of the single-quote character `'`.

We can insert a new record containing a single quote, for instance a last-name of `O'Brien`.  Soul accepts this.

But, it we try to push an edit to the that field, or use the single-quote in a `_search` parameter, Soul returns an error.

Here is the `GET` URL: `http://localhost:8000/api/tables/invoices/rows?_search=O%27Brien`

This is the Soul response:
![image](https://github.com/thevahidal/soul/assets/1108513/4ca4276f-c98b-4234-9ffc-ec21b87ba85a)

Does this character need to escaped before it is processed?

**Comment by thevahidal** [comment]
Hey @IanMayo,
Yes, you should escape it using two single quotations, so instead of `O'Brien` you should use `O''Brien`.

**Comment by thevahidal** [comment]
Though we can do this inside Soul itself.

**Comment by IanMayo** [comment]
Great, thanks. Hmm, I guess we have a choice on whether to hide or expose this SQL pattern.

I think it would be good if Soul could invisibly handle it, so it's one less thing for the Soul user to think/worry about.

**Comment by thevahidal** [comment]
Sure, I'll work on it.
