### ISSUE TITLE
Serve static files over express server

### ISSUE THREAD

**Issue by faisalsiddique4400** [thevahidal/soul#161]
**Is your feature request related to a problem? Please describe.**
Soul currently lacks support for serving static media files. It is essential to implement a configuration option in Soul to enable the serving of static files.

**Describe the solution you'd like**
A customizable feature, similar to extensions, should be provided, allowing users to specify a folder path for serving its contents statically.

**Additional context**
This wrapper is highly compatible with react-admin. If react-admin facilitates handling the upload of media files (such as images) and storing their URLs in the database, Soul should also provide a mechanism to serve these media files. This issue aims to bring attention to the absence of this particular feature in Soul.

**Comment by IanMayo** [comment]
Hello @faisalsiddique4400 , I'm pretty sure my team has implemented a working instance of this using `_extensions`, without requiring any changes to `soul-cli`.  We're serving a compiled `react-admin` app as static html content from a `soul-cli` instance.

We've got a lot on right now, but I hope to provide a walkthrough in a few days.

**Comment by thevahidal** [comment]
@IanMayo I'm closing this issue as it's been a while, please open it whenever you find the time to provide the walkthrough.

**Comment by thevahidal** [comment]
Hi @faisalsiddique4400, 
@AbegaM is working on a new PR about how to serve static files over Soul. Check out #208 for instructions.
