### ISSUE TITLE
Bug: bad links on web page

### ISSUE THREAD

**Issue by suryavirkapur** [thevahidal/soul#167]
**Describe the bug**
Malfunctioning links

**To Reproduce**
1. Go to 'A clear and concise description of what the bug is.'
2. Click on '/api/tables' or any of the other links that start with 'api'
3. See error

**Expected behavior**
Sends me to the correct website.

**Comment by IanMayo** [comment]
Hello @suryavirkapur - I'd like to help out, but I can't quite reproduce what you are seeing - or understand where you are experiencing the issue.

Could your step `1.` be mistaken, it appears to be copy/pasted text.

**Comment by thevahidal** [comment]
Hi @suryavirkapur,
Soul static page is fixed, give it a try and let me know if you faced any issues!
