### ISSUE TITLE
Example of auth requests

### ISSUE THREAD

**Issue by austinkottke** [thevahidal/soul#195]
So how does one execute a request with curl in auth? Does the documentation provide any examples of doing a request with authentication.

{"message":"Invalid access token"}

**Comment by thevahidal** [comment]
Hi @austinkottke,
You need to first create a user to obtain a token using login endpoint and then pass access token via cookie to the request.
I'll try to provide an example as soon as I find some free time.

**Comment by thevahidal** [comment]
Hey @austinkottke,
I just created a new PR (#197) regarding the auth endpoint examples.
Please take a look at it and let me know if anything is not explained well.

**Comment by austinkottke** [comment]
Thanks -- looks great. Very clear.

**Comment by thevahidal** [comment]
@austinkottke 
#197 is merged!
