### ISSUE TITLE
Can we please remove better-sqlite3

### ISSUE THREAD

**Issue by thoughtsunificator** [thevahidal/soul#213]
Other than forcing us to use a specific Node.js version along with many system requirements  (python, build-essential and much more) and causing the npm install to hang for 10 minutes it's useless.

For obvious reasons better-sqlite3 is crap and it has nothing to do in the Node.js ecosystem.

**Comment by thoughtsunificator** [comment]
For the time being you can avoid all the pain by using the following

```Dockerfile
# node:19-alpine
FROM node@sha256:d0ba7111bc031323ce2706f8e424afc868db289ba40ff55b05561cf59c123be1 AS node

WORKDIR /app

ENV NODE_ENV="production"

COPY package-lock.json package.json ./

RUN apk update && apk add python3=3.11.10-r1 build-base=0.5-r3 && npm ci

COPY . .

CMD [ "npm", "start" ]


```

**Comment by thevahidal** [comment]
Hey @thoughtsunificator,
Can you make a PR for the Dockerfile?
