### ISSUE TITLE
dev experience when running on empty db

### ISSUE THREAD

**Issue by arnorhs** [thevahidal/soul#47]
Hey, I saw your post on HN and was curious, and have a bunch of random feedback.

I followed the readme for getting things set up. However, I didn't have an sqlite db lying around, so i made an empty one.

Studio started on a different port than 3000, probably because I'm running a different dev server on 3000, so I got a cors error when running on this different port. Possibly set cors origins to allow * in dev?

Besides that running studio I got some semi-broken UI, probably because my db is empty, and errors in console. I fixed some of them locally but ended up getting too many retries (http) errors and ended up giving up 😭 

Anyways.. mostly a feedback around "maybe you should try to get it working with an empty db file" ?

Anyways, the concept is nice, good luck and keep it up

**Comment by thevahidal** [comment]
Hi @arnorhs,
Thanks for checking out Soul and also sorry for the poor experience you had with Studio. As I mentioned in HN, studio is really at the beginning steps.
If you don't have any db and want to create a fresh one you can simply do `soul -d newdb.db` and Soul automatically generates one with the same name.
About the example you're totally right, I need to add it.
Thanks again.

**Comment by thevahidal** [comment]
@arnorhs ,
By the way for the cors issue you need to update your `.env` variables in `core` directory:
```
CORS_ORIGIN_WHITELIST=http://localhost:3456
```
