### ISSUE TITLE
Fails with missing port on both Windows and Linux

### ISSUE THREAD

**Issue by maacl** [thevahidal/soul#48]
Following README starting soul fails on both Windows and Linux as follows:

```
❯ soul -d sqlite.db -p 8000
/mnt/c/Users/marti/AppData/Roaming/npm/node_modules/soul-cli/soul/config/index.js:32
  throw new Error(`Config validation error: ${error.message}`);
  ^

Error: Config validation error: "PORT" is required
```

**Comment by thevahidal** [comment]
Hi @maacl,
Thanks for testing Soul.
I checked it out and the problem was that the config was not considering CLI args while validating.
I fixed it and i'll merge to main.
You need to install the new version (v0.0.3).

**Comment by maacl** [comment]
Thanks. After upgrade it fails with:
