### ISSUE TITLE
Any specific usage scenarios for this?

### ISSUE THREAD

**Issue by bytemain** [thevahidal/soul#54]
Thanks for creating this tool.

I'm just curious and want to know what this tool can be used.

Thanks for sharing.

**Comment by thevahidal** [comment]
Hi @bytemain,
Thanks for checking out Soul,
To name a few useful usages:
1. A simple backend-as-a-server: Right now it's too minimal but after adding authentication and permission levels you can easily have a RESTful backend.
2. Access DB without SQL: Soul lets you read from and write to your DB without any SQL knowledge.
