### ISSUE TITLE
Support full set of REST calls expected by react-admin

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#57]
The combination of a `react-admin` interface for a `SQLite` backend could be a really lightweight solution to many problems. But, there isn't (yet) a REST wrapper for SQLite that is capable of integrating with `react-admin`

It now looks like `soul` may be the missing component to getting this working.  But, the Soul API needs to be extended, just a little:
https://marmelab.com/react-admin/DataProviderWriting.html#request-format

**Comment by thevahidal** [comment]
Hi @IanMayo,
Thanks for checking out Soul.
From what I saw we need to add bulk actions (update and delete) to Soul to be compatible with react-admin.
Bulk endpoints are in my mind and I can prioritize them if you're willing to work on the react-admin API provider.

**Comment by thevahidal** [comment]
@IanMayo,
I just added bulk endpoints. It's available in v0.0.8.

**Comment by IanMayo** [comment]
Now that's an impressive turnaround @thevahidal 

It looks like `soul` still needs `getMany` and `getManyReference`.

I'm pretty sure `react-admin` uses these to get the data involved in `one-to-many` relationships.  Imagine the user wants to view a page of 10 music tracks which contain a foreign key for the album, but the app must display the album title.  There will need to be a REST query to get the albums data.   It would be a waste to retrieve the full list of albums if only 3 are required, better to just call `http://my.api.url/albums?filter={"ids":[123,456,789]}`

**Comment by thevahidal** [comment]
@IanMayo,
I will add bulk retrieve too.
For the related fields, Soul already support extending foreign keys with `_extend` query parameter, available for list and retrieve endpoints.

**Comment by thevahidal** [comment]
I need to update the endpoints though, I think `/bulk` is not that good, I'll go with `/1,2,3` (where 1, 2, 3 are the ids).

**Comment by IanMayo** [comment]
Hello @IanMayo - I haven't seen `_extend` in a REST API before.  I can understand why you've done it.

But, in your example, there is an inevitable duplication of the Iron Maiden data:
![image](https://user-images.githubusercontent.com/1108513/199948054-5b9634cc-4f08-4deb-a850-c22a8f2c2ab1.png)

**Comment by thevahidal** [comment]
@IanMayo,
We have another query param `_schema` which let's user only get the fields he intended for example `?_schema=AlbumId,Title` which right now doesn't work on `_extend`ed fields but my goal is to make it work for these too, e.g. `_schema=AlbumId,Title,ArtistId{Name}`.

About the extending, I couldn't find a better way to do it. Please let me know if you know a more intuitive way to do it.

Also, I totally appreciate your help! Thanks for helping to make Soul a better tool.

**Comment by thevahidal** [comment]
@IanMayo,
Btw I just released v0.0.9 which adds bulk mode support in retrieve, update and delete endpoints and there's no extra endpoints for it.
And the endpoints are like this now:
- `/tables/singers/rows/1`: To retrieve (or update and delete) a single row 
- `/tables/singers/rows/1,2,3`: To retrieve (or update and delete) multiple rows

**Comment by IanMayo** [comment]
> Please let me know if you know a more intuitive way to do it.

I know it's two calls, but I think the `1,2,3` could be a tidy way of doing it.   As the client app is collating the `Tracks` data, it get the `tracks/_filters=RockGod:true`.  Then it loops through the rows and collates the `Albums` it needs data about then calls `albums/1,3,4?_schema=AlbumId, Title` (or something like that :-).  If there is only one `albumId` (`albums/4`) then the call may even have been cached - one of the aims of REST.
