### ISSUE TITLE
Declare shiny new `Automatic-API`

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#61]
A github repo is acting as an `index` of libraries that expose HTML apis for databases:
https://github.com/dbohdan/automatic-api

An entry should be added for `soul`.

**Comment by thevahidal** [comment]
@IanMayo,
Thanks for the suggestion, I'll create a PR in automatic-api!

**Comment by IanMayo** [comment]
I was going to do it myself - but you can _sell_ `soul` better :-) .

**Comment by thevahidal** [comment]
Thanks @IanMayo,
Here's the PR https://github.com/dbohdan/automatic-api/pull/39
