### ISSUE TITLE
Soul must be extendable

### ISSUE THREAD

**Issue by thevahidal** [thevahidal/soul#65]
To be able to be adapted to any needs, Soul needs to be extendable, because no matter how many built-in features it offers, eventually, people come with unique needs that the Soul can't and shouldn't have an answer for them.

For now, I'm thinking of three types of extensions:
1. API extensions: A way to add new APIs besides the default ones
   - e.g. `/api/greeting` which returns a greeting message.
2. Middleware extensions:
   - e.g. Auth middleware which forces authentication on endpoints. 
 3. Callback extensions:
    - e.g. After adding a row do an action

**Comment by IanMayo** [comment]
Hello @thevahidal - I'm starting to think about protection/authentication of our Soul instance.

Did you have any further thoughts on the Auth middleware?  I/we may be able to help out with the implementation.

**Comment by thevahidal** [comment]
I'll close this issue and we can continue our discussion in this one https://github.com/thevahidal/soul/issues/4#issuecomment-1643704099
