### ISSUE TITLE
Host static web-content

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#75]
**Is your feature request related to a problem? Please describe.**

I'm trying to run `react-admin` against a SQLite file wrapped in `Soul`.  But, I'm having CORS issues.  I saw the `.env.sample` file - containing the WHITELIST, and renamed it to `.env` - but it didn't fix the issue.  Yes, the URL in the file matches the actual origin (`localhost:3000`) of my node server.  **Update:** a few minutes later the CORS issue is resolved. Silly Ian mistakenly tried to modify the behaviour of an installed instance of Soul by modifying a file in a source repo.  When I ran Soul from the repo the `.env` trick worked perfectly :-)

I remain interested in the idea of running static content from within `Soul`.

**Describe the solution you'd like**

One solution for the above would be for the Soul server to host static web content in a sub-folder.  This would _neatly_ prevent my CORS issues, and result in one less server process (node) running on my machine.

**Describe alternatives you've considered**

**Additional context**
Hmm, on reflection would an `extension` be a way to do this?  We'd create an extension called `root`, that serves `index.html` from the `root` folder. Would that do it @thevahidal ?

**Comment by thevahidal** [comment]
Hi @IanMayo,
I'm glad that you fixed your first issue. 
About serving static files, I'm not sure if it fits into the scope of what Soul is supposed to do. 
I'll take a look into what solutions we have to approach this problem. I'll let you know if anything came to my mind.
