### ISSUE TITLE
The `extensions.js` file throws an error when i try to run an extension

### ISSUE THREAD

**Issue by AbegaM** [thevahidal/soul#77]
**Describe the bug**

I am trying to run a soul extension inside the `soul/core` folder but the code is throwing an error in the `/core/src/extensions.js` file, i have followed the instructions in [here](https://github.com/thevahidal/soul/blob/main/docs/extensions-examples.md) to run the extension. 

**To Reproduce**

1. Go to the `soul/core` folder and create a folder named `_extensions`

2. Create a file named `api.js` inside the `_extensions` folder and copy and paste the sample extension code from [here](https://github.com/thevahidal/soul/blob/main/docs/extensions-examples.md)

3. Add the path of your extension in your `.env` file 

   ```
   EXTENSIONS=./_extensions
   ```

4. Run the project 

   ```
   npm run dev
   ```

**Expected behavior**
When i run the project, it throws an error in this [line](https://github.com/thevahidal/soul/blob/5859d5e63de995d31156752b96c42208f808e098/core/src/extensions.js#L12), it can't `require` the `_extensions/api.js` file, 

**Screenshots**
![Screen Shot 2022-12-10 at 10 58 50 PM](https://user-images.githubusercontent.com/70259638/206873156-269ac5f7-3d8d-47a9-84a6-b0761e22a078.png)

**Additional context**
The code works fine when i modify the path of the extension like this

```js
- const apiExtensions = require(`${extensionsPath}/${extension}`);

+ const apiExtensions = require(`../${extensionsPath}/${extension}`);
```

**Comment by thevahidal** [comment]
Hi @AbegaM,
you should provide the "absolute" path.
e.g. `EXTENSIONS=/home/user/soul/core/_extensions`

**Comment by thevahidal** [comment]
Just updated the https://github.com/thevahidal/soul/blob/main/docs/extensions-examples.md to mention the importance of absolute paths for the `extensions` directory.

**Comment by AbegaM** [comment]
@thevahidal Thank you so much for your answer. I just changed it to an absolute path and everything is working fine now.

**Comment by IanMayo** [comment]
Hello @thevahidal - is there a strong technical reason why the path has to be absolute?

It can make deployment of a Soul-based solution more challenging - including the fact that extensions will not work "out of the box" on a clone of the repo (since we can't forecast the directory structure above the repo).

**Comment by thevahidal** [comment]
> Hey @IanMayo, No there's not a strong reason behind it, it was just easier as Soul is basically a CLI. But I can change it so it supports relative paths from where you run the CLI.

Issue created.
https://github.com/thevahidal/soul/issues/78
