### ISSUE TITLE
Support Support for multiple sqlite files

### ISSUE THREAD

**Issue by BillMeyerRSA** [thevahidal/soul#79]
In cases where there are multiple sqlite files in use, it would be good to be able to serve API for multiple databases. Perhaps a json config file to be able to set parameters.

**Comment by BillMeyerRSA** [comment]
Maybe add list of databases in directory to array:

// get all sqlite databases in the filepath and add to array
const getAllFiles = function(dirPath, arrayOfFiles) {
  files = fs.readdirSync(dirPath)
  arrayOfFiles = arrayOfFiles || []
  files.forEach(function(file) {
    if (fs.statSync(dirPath + "/" + file).isDirectory()) {
      arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles)
    } else {
      arrayOfFiles.push(path.join(__dirname, dirPath, "/", file))
    }
  })
  return arrayOfFiles
}

And then serve API in path /databasename/API

**Comment by thevahidal** [comment]
Hey @BillMeyerRSA,
Thanks for the suggestion but currently I don't think that supporting multiple SQLite files is of the highest priority for Soul, Though I welcome your PRs if you see it's good fit and you wanna put the effort on achieving that.
