### ISSUE TITLE
Question: does soul support string identifiers

### ISSUE THREAD

**Issue by IanMayo** [thevahidal/soul#97]
The soul API examples all use integer index values:
```
curl http://localhost:8000/api/tables/Album/rows/1/
```

I believe the REST standard allows for string index values.  The database I wish to "wrap" with Soul includes some string index values.   My developer has warned that Soul is failing for string indices.

Should Soul support URLs like this?
```
curl http://localhost:8000/api/tables/Country/rows/usa/
```

**Comment by thevahidal** [comment]
Hey @IanMayo,
If you read through comments inside `rows` controller, you'll see that by default it accepts the primary key field as the identifier, but you can pass the `_lookup_field` query parameter to change it to whatever field you need.

**Comment by IanMayo** [comment]
Hello @thevahidal ,
but can the primary key field be a string value?  It appears that the API can only support integers in the primary key.  In the mock example for the original post I'm proposing that the `Country` table has strings as the primary key, instead of integers.

**Comment by thevahidal** [comment]
Yes primary keys can be strings. In the mock example I just used a simple usage, but you can have string primary keys and query using them.
Though you can consider the `_lookup_field` query parameter as it's a more verbose option.

**Comment by IanMayo** [comment]
My dev is going to produce a reproducible example using `chinook.db`. But, from what he has seen so far, it appears multiple rows can be requested using integer ids, but not string ids:
![image](https://github.com/thevahidal/soul/assets/1108513/df158d07-e450-4773-9037-1e1d699e6d5c)

Note `org-1`, `org-2` and so on are the string-based primary keys in one of our tables.

**Comment by IanMayo** [comment]
Please find attached a modified chinook database, with a `countries` table that has a string-based primary key:
[chinook.db.zip](https://github.com/thevahidal/soul/files/12037648/chinook.db.zip)

These are the responses for various URLs:

`http://localhost:3000/api/tables/countries/rows`
```
{"data":[{"id":"usa","population":12000},{"id":"france","population":3000},{"id":"england","population":4000},{"id":"denmark","population":6000}],"total":4,"next":null,"previous":null}
```

`http://localhost:3000/api/tables/countries/rows/usa/`
```
{"message":"no such column: usa","error":{"code":"SQLITE_ERROR"}}
```

`http://localhost:3000/api/tables/countries/rows/usa,france/`
```
{"message":"no such column: usa","error":{"code":"SQLITE_ERROR"}}
```
