### ISSUE TITLE
Separate Soul Core and Studio Repositories

### ISSUE THREAD

**Issue by thevahidal** [thevahidal/soul#98]
**Is your feature request related to a problem? Please describe.**
Right now Core and Studio reside in this repo, making the CI process a bit hard and messy. 
 
**Describe the solution you'd like**
It's time to separate them into two isolated reports.

**Describe alternatives you've considered**
No other alternative can fix this issue.

**Additional context**
We should create a new repo for studio and keep core here.

**Comment by IanMayo** [comment]
Note: once this is done, `core` can sit at the root of the repo, and it should be really easy to provide a deployment of each PR in Heroku, for review/test.

**Comment by thevahidal** [comment]
@IanMayo Thanks for the reminder, to prevent conflicts with the work that @AbegaM is doing right now, we can finish that PR and then stop doing any new stuff and just separate core and studio for good. 
What do you think about this?

**Comment by thevahidal** [comment]
Yeah I'm confident that it's going to be a quick process
